### ISSUE TITLE
Why is helmet necessary?

### ISSUE THREAD

**Issue by wallawe** [CodementorIO/nextjs-redux-starter#1]
Since you can already customize what's in the head by [importing 'next/head' and customizing](https://github.com/zeit/next.js/blob/canary/examples/head-elements/pages/index.js), is helmet necessary? Thanks for any advice, I'm trying to figure out whether I should gut helmet or if there's an edge case I'm not thinking of.

**Comment by IanWang** [comment]
since there're still [some bugs](https://github.com/zeit/next.js/issues?utf8=%E2%9C%93&q=is%3Aissue+head+is%3Aopen+) when using `next/head` like [this](https://github.com/zeit/next.js/issues/3575) and [this](https://github.com/zeit/next.js/issues/3527), so I'd prefer using `react-helmet` at the moment. 
and also `next/head` requires adding `key` prop to prevent duplicate tag which is a little bit annoying. (you might easily forget and introduce a SEO bug without knowing)
